-- B8: the customer negotiates in a portal that is a different application, not a
-- filtered view of this one.

-- The portal never receives a numeric quotation id. It gets this, and the real id comes
-- from the token rather than the URL -- which removes guessing another customer's
-- quotation as a category of attack rather than defending against it.
alter table quotation add column public_ref uuid not null default gen_random_uuid();
alter table quotation add column sent_at timestamptz;

-- The score the quotation carried when it was last approved. Re-approval after a
-- negotiation compares against this rather than zero, or every trivial edit would drag
-- the whole chain through again.
alter table quotation add column approved_baseline_score int;

create unique index uq_quotation_public_ref on quotation (public_ref);

/*
 * A magic link, and the session it becomes.
 *
 * The link is 256 bits of randomness, stored only as a SHA-256 hash, single use and
 * bound to one customer and one quotation. Verifying it burns it and mints a session
 * token on the same row -- so a leaked link is worth nothing once opened, and a leaked
 * database is worth nothing at all.
 */
create table portal_token (
    id                  bigint      generated by default as identity primary key,
    token_hash          varchar(64) not null unique,
    customer_id         bigint      not null references customer (id),
    quotation_id        bigint      not null references quotation (id) on delete cascade,
    expires_at          timestamptz not null,
    used_at             timestamptz,
    session_hash        varchar(64) unique,
    session_expires_at  timestamptz,
    created_at          timestamptz not null default now()
);

create index idx_portal_token_quotation on portal_token (quotation_id);

/** One thread per quotation, both sides of the conversation in it. */
create table negotiation_msg (
    id           bigint       generated by default as identity primary key,
    quotation_id bigint       not null references quotation (id) on delete cascade,
    -- Null when the message is about the order rather than one line.
    line_id      bigint       references quotation_line (id) on delete set null,
    author       varchar(20)  not null check (author in ('CUSTOMER', 'SALES')),
    author_name  varchar(160) not null,
    body         varchar(2000) not null,
    created_at   timestamptz  not null default now()
);

create index idx_negotiation_msg_quotation on negotiation_msg (quotation_id, id);

-- The customer's outstanding proposal. One per quotation: a new counter replaces the
-- last, because what matters is what they are asking for now.
create table negotiation_counter (
    id           bigint         generated by default as identity primary key,
    quotation_id bigint         not null unique references quotation (id) on delete cascade,
    discount_pct numeric(5, 2)  not null,
    note         varchar(1000),
    state        varchar(20)    not null,
    proposed_at  timestamptz    not null default now()
);
