-- A2: the catalog the brief actually asks for -- twelve products, variants, and price
-- lists, with one resolution order behind every price a customer is quoted.
--
-- Resolution runs base -> variant -> price list, each layer overriding the one before.
-- The base price is the best rate in the system: the largest customers pay it, and the
-- smaller tiers sit on published lists above it. That is why Gold has no list -- it is
-- already on the keenest price, and its advantage shows up again in a wider discount
-- ceiling.

insert into product (id, name, category_id, unit_price, unit_cost) values
    (6,  'Ultrawide Monitor',    1,  32000,  21000),
    (7,  'Wireless Keyboard',    1,   4500,   2600),
    (8,  'Server Rack',          1, 140000,  98000),
    (9,  'Data Migration',       2,  45000,  28000),
    (10, 'Premium Support Plan', 3,   6000,   2100),
    (11, 'Analytics Add-on',     3,   3500,   1200),
    (12, 'Security Audit',       2,  60000,  39000);

-- The new physical goods need shelves; services and subscriptions never do.
insert into stock_item (warehouse_id, product_id, quantity) values
    (1, 6, 12), (2, 6, 20),
    (1, 7, 60), (2, 7, 90),
    (1, 8,  2), (2, 8,  4);

/*
 * A variant is the same product in a different shape. It carries its own price and cost
 * rather than a delta, so a price is always read rather than computed from a chain of
 * adjustments nobody can follow.
 */
create table product_variant (
    id         bigint        generated by default as identity primary key,
    product_id bigint        not null references product (id),
    name       varchar(120)  not null,
    unit_price numeric(14, 2) not null,
    unit_cost  numeric(14, 2) not null,
    constraint uq_variant_product_name unique (product_id, name)
);

insert into product_variant (product_id, name, unit_price, unit_cost) values
    (1, '16GB / 512GB',  80000,  58000),
    (1, '32GB / 1TB',    96000,  69000),
    (6, '34-inch',       32000,  21000),
    (6, '38-inch',       41000,  27000),
    (8, '24U',          140000,  98000),
    (8, '42U',          185000, 129000);

create table price_list (
    id      bigint       generated by default as identity primary key,
    name    varchar(120) not null unique,
    -- Null would mean a list that applies to everyone; every seeded list is tier-bound.
    tier_id bigint       references customer_tier (id),
    active  boolean      not null default true
);

-- At most one live list per tier, enforced here rather than in a service that could be
-- bypassed. Two active lists for one tier would make a price ambiguous.
create unique index uq_price_list_active_tier on price_list (tier_id) where active;

create table price_list_item (
    id            bigint         generated by default as identity primary key,
    price_list_id bigint         not null references price_list (id) on delete cascade,
    product_id    bigint         not null references product (id),
    unit_price    numeric(14, 2) not null,
    constraint uq_price_list_product unique (price_list_id, product_id)
);

-- Tier 1 Bronze, 2 Silver, 3 Gold.
insert into price_list (id, name, tier_id) values
    (1, 'Standard', 1),
    (2, 'Growth',   2);

insert into price_list_item (price_list_id, product_id, unit_price) values
    -- Standard, for Bronze
    (1, 1,  88000), (1, 4, 13500), (1, 6, 35500), (1, 8, 156000),
    -- Growth, for Silver
    (2, 1,  84000), (2, 4, 12800), (2, 6, 33500), (2, 8, 148000);
