-- B9. Three detectors, one alert table.

create table deal_health_alert (
    id           bigint       generated by default as identity primary key,
    quotation_id bigint       not null references quotation (id) on delete cascade,
    type         varchar(30)  not null,
    severity     varchar(10)  not null,
    -- Written when the alert is raised, so the card can say why this particular deal was
    -- flagged rather than what the detector does in general.
    explanation  varchar(500) not null,
    -- The figures behind an anomaly: the discount, the rep's own mean and sigma, how many
    -- quotes it was drawn from, and whether the team's numbers had to stand in.
    payload_json text,
    opened_at    timestamptz  not null default now(),
    acked_at     timestamptz,
    resolved_at  timestamptz
);

/*
 * The index that makes the detectors safe to re-run.
 *
 * Without it every dashboard load would raise a fresh alert for the same stalled deal.
 * With it, a second insert for a pair that is already open simply fails and is skipped --
 * so "run the detectors" is idempotent by construction rather than by a service
 * remembering to check first.
 */
create unique index uq_alert_open_per_quotation_type
    on deal_health_alert (quotation_id, type) where resolved_at is null;

create index idx_alert_open on deal_health_alert (resolved_at, severity);
