-- A1. Identity, at last.
--
-- Every endpoint until now took ?userId= and believed it. The role checks throughout the
-- services were real, but they were checking a claim the caller made about themselves --
-- anyone could be Finance by editing a query string. These two columns are what make those
-- checks mean what they have always looked like they meant.

alter table app_user add column email varchar(160);
alter table app_user add column password_hash varchar(72);

/*
 * One bcrypt hash of "demo1234", shared by every seeded account.
 *
 * A shared demo password is a deliberate simplification and worth naming as one: it is
 * here so a reviewer can sign in as each role in seconds. The hash is real -- generated by
 * the same BCryptPasswordEncoder the application authenticates with -- rather than a
 * placeholder, so login works from a clean clone with nothing to set up.
 */
update app_user set
    password_hash = '$2a$10$7wIRrX6Lko0GiSynMNeW5OimEcNXFmD4R6w62MeeXdIJQCEvuDYoi',
    email = case id
        when 1 then 'rep@dealflow.test'
        when 2 then 'manager@dealflow.test'
        when 3 then 'finance@dealflow.test'
        when 4 then 'priya@dealflow.test'
        when 5 then 'arjun@dealflow.test'
        when 6 then 'nina@dealflow.test'
        else 'user' || id || '@dealflow.test'
    end;

-- Only now that every row has one. Adding these as not-null up front would have failed
-- against the six users already in the table.
alter table app_user alter column email set not null;
alter table app_user alter column password_hash set not null;

-- An email identifies an account, so two accounts cannot share one.
create unique index uq_app_user_email on app_user (lower(email));
