-- Section A, the write side. Four things the config screens need that the schema could not
-- express: server-assigned ids, an archive flag where rows are referenced by history, and a
-- subscription plan to hold the three billing choices that were previously hardcoded.

-- Several seed files insert explicit ids into identity columns -- price_list 1 and 2,
-- quotation 100..139 and 200..203, approval_request 900..902. Postgres does not advance a
-- sequence for an explicit insert, so every one of those sequences is still parked at 1 and
-- the next generated id collides with a seeded row. price_list collides on the very first
-- create; quotation would have collided silently at the hundredth. Wind each sequence past
-- the largest id its table actually holds.
do $$
    declare
        seq    record;
        max_id bigint;
    begin
        for seq in
            select c.relname                                       as table_name,
                   a.attname                                       as column_name,
                   pg_get_serial_sequence(c.relname, a.attname)     as sequence_name
            from pg_class c
                     join pg_namespace n on n.oid = c.relnamespace
                     join pg_attribute a on a.attrelid = c.oid and a.attnum > 0
            where n.nspname = current_schema()
              and c.relkind = 'r'
              and a.attidentity <> ''
            loop
                execute format('select coalesce(max(%I), 0) from %I',
                               seq.column_name, seq.table_name) into max_id;
                if max_id > 0 then
                    perform setval(seq.sequence_name, max_id);
                end if;
            end loop;
    end
$$;

-- Ids were assigned by hand in the seed files, which is fine for seed data and impossible
-- for a create endpoint. Start these two at 100 so the seeded 1..12 stay stable and every
-- fixture, brief and published figure keeps resolving. After the sweep above, so the 100
-- wins rather than being overwritten by the seeded maximum.
alter table product alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('product', 'id'), 100, false);

alter table warehouse alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('warehouse', 'id'), 100, false);

-- Products, price lists and warehouses are referenced by quotations, invoices and stock
-- history. Deleting one would orphan real records, so a delete archives: it leaves the
-- catalog, and everything already pointing at it still resolves.
alter table product add column archived boolean not null default false;
alter table price_list add column archived boolean not null default false;
alter table warehouse add column archived boolean not null default false;

-- The partial unique index on an active list per tier has to ignore archived lists, or an
-- archived Silver list would block a new one.
drop index uq_price_list_active_tier;
create unique index uq_price_list_active_tier
    on price_list (tier_id) where active and not archived;

-- A5. Recurring billing hardcoded three decisions: calendar-month periods, prorate on a
-- mid-period change, credit note on cancel. A plan makes those three explicit and editable.
create table subscription_plan (
    id                  bigint       generated by default as identity primary key,
    name                varchar(120) not null,
    product_id          bigint       not null references product (id),
    -- "interval" is reserved in Postgres
    interval_unit       varchar(20)  not null,
    proration_policy    varchar(30)  not null,
    cancellation_policy varchar(30)  not null,
    active              boolean      not null default true
);

-- A product prices one way at a time. Two active plans would make a period ambiguous.
create unique index uq_plan_active_product on subscription_plan (product_id) where active;

-- Every recurring product starts on a plan that reproduces exactly what billing does today,
-- so nothing about the existing billing screens or their figures moves until an admin
-- deliberately changes a policy.
insert into subscription_plan (name, product_id, interval_unit, proration_policy,
                               cancellation_policy)
select p.name || ' Monthly', p.id, 'MONTHLY', 'PRORATE', 'IMMEDIATE_WITH_CREDIT'
from product p
         join product_category c on c.id = p.category_id
where c.recurring;
