-- DealFlow360 prototype schema. 11 tables, not 26 -- the rest arrive with later phases.
-- Money is NUMERIC(14,2), percentages NUMERIC(5,2). No float, no double, anywhere.

create table app_user (
    id   bigint primary key,
    name varchar(120) not null,
    role varchar(20)  not null check (role in ('REP', 'MANAGER', 'FINANCE'))
);

create table customer_tier (
    id          bigint primary key,
    name        varchar(60)   not null,
    ceiling_pct numeric(5, 2) not null
);

create table customer (
    id      bigint primary key,
    name    varchar(160) not null,
    tier_id bigint       not null references customer_tier (id)
);

create table product_category (
    id          bigint primary key,
    name        varchar(60) not null,
    -- nullable on purpose: a category without a ceiling falls back to the tier ceiling
    ceiling_pct numeric(5, 2)
);

create table product (
    id          bigint primary key,
    name        varchar(160)   not null,
    category_id bigint         not null references product_category (id),
    unit_price  numeric(14, 2) not null,
    unit_cost   numeric(14, 2) not null
);

create table quotation (
    id                 bigint generated by default as identity primary key,
    customer_id        bigint        not null references customer (id),
    rep_id             bigint        not null references app_user (id),
    state              varchar(30)   not null,
    risk_score         int           not null default 0,
    order_discount_pct numeric(5, 2) not null default 0,
    last_activity_at   timestamptz   not null default now(),
    created_at         timestamptz   not null default now()
);

create table quotation_line (
    id           bigint generated by default as identity primary key,
    quotation_id bigint        not null references quotation (id) on delete cascade,
    product_id   bigint        not null references product (id),
    quantity     int           not null check (quantity > 0),
    discount_pct numeric(5, 2) not null default 0
);

create table approval_request (
    id           bigint generated by default as identity primary key,
    quotation_id bigint      not null references quotation (id) on delete cascade,
    risk_score   int         not null,
    state        varchar(20) not null,
    created_at   timestamptz not null default now()
);

create table approval_step (
    id         bigint generated by default as identity primary key,
    request_id bigint      not null references approval_request (id) on delete cascade,
    step_order int         not null,
    role       varchar(20) not null,
    state      varchar(20) not null,
    decided_by bigint references app_user (id),
    reason     varchar(500),
    decided_at timestamptz
);

create table audit_event (
    id           bigint generated by default as identity primary key,
    quotation_id bigint       not null references quotation (id) on delete cascade,
    actor_id     bigint references app_user (id),
    action       varchar(60)  not null,
    from_state   varchar(30),
    to_state     varchar(30),
    reason       varchar(500),
    created_at   timestamptz  not null default now()
);

create table system_config (
    key   varchar(80) primary key,
    value varchar(120) not null
);

create index idx_quotation_state on quotation (state);
create index idx_line_quotation on quotation_line (quotation_id);
create index idx_audit_quotation on audit_event (quotation_id, created_at);
