-- A rep meets a new company while building a quotation, so a customer has to be creatable
-- from the quote builder rather than only by hand in the seed.
--
-- customer.id was declared in V1 as a plain bigint primary key, the way product and
-- warehouse were before V16. Ids assigned by hand are fine for seed data and impossible
-- for a create endpoint: nothing hands out the next one. The same conversion V16 applied
-- to those two applies here, for the same reason and with the same starting point.
--
-- Start at 100 so the seeded 1, 2 and 3 stay stable. V2 seeds Acme, Beta and Corex at
-- those ids and V12's demo history points forty quotations at them, so moving them would
-- silently re-attribute the history the briefs and the walkthrough both quote.
alter table customer alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('customer', 'id'), 100, false);
