-- Fulfilment: where stock lives, and how an order gets split across warehouses.

create table warehouse (
    id                 bigint primary key,
    name               varchar(120)   not null,
    -- Fixed cost of despatching anything at all from here. Dominates the cost model
    -- on purpose: the algorithm should prefer one shipment over two.
    shipment_fee       numeric(14, 2) not null,
    -- Per-unit cost multiplier. Breaks ties between warehouses that could both serve.
    shipping_weight    numeric(6, 2)  not null,
    -- How long a restock takes here; a backorder is promised today + this.
    replenishment_days int            not null
);

create table stock_item (
    id           bigint generated by default as identity primary key,
    warehouse_id bigint not null references warehouse (id),
    product_id   bigint not null references product (id),
    quantity     int    not null check (quantity >= 0),
    constraint uq_stock_warehouse_product unique (warehouse_id, product_id)
);

-- One accepted plan per quotation. A suggestion is computed on demand and never stored.
create table allocation_plan (
    id             bigint generated by default as identity primary key,
    quotation_id   bigint         not null unique references quotation (id) on delete cascade,
    shipment_count int            not null,
    estimated_cost numeric(14, 2) not null,
    overridden     boolean        not null default false,
    consolidatable boolean        not null default false,
    created_at     timestamptz    not null default now()
);

create table allocation_line (
    id           bigint generated by default as identity primary key,
    plan_id      bigint not null references allocation_plan (id) on delete cascade,
    product_id   bigint not null references product (id),
    warehouse_id bigint not null references warehouse (id),
    quantity     int    not null check (quantity > 0)
);

create table backorder (
    id            bigint generated by default as identity primary key,
    plan_id       bigint not null references allocation_plan (id) on delete cascade,
    product_id    bigint not null references product (id),
    quantity      int    not null check (quantity > 0),
    promised_date date   not null
);

create index idx_stock_product on stock_item (product_id);
create index idx_alloc_line_plan on allocation_line (plan_id);
create index idx_backorder_plan on backorder (plan_id);
