-- A3 requires that policy edits are logged with who changed what, and when.
--
-- The summary is generated from the diff -- "Gold tier ceiling 15% to 10%" -- rather than
-- typed by the user. A typed note can be left blank or describe something other than what
-- actually changed; a generated one cannot.

create table policy_change (
    id         bigint        generated by default as identity primary key,
    actor_id   bigint        references app_user (id),
    summary    varchar(1000) not null,
    created_at timestamptz   not null default now()
);

-- The screen shows newest first and never pages, so one descending index serves every read.
create index idx_policy_change_created on policy_change (created_at desc);
