-- A6 / B5: what else to put on this order.
--
-- Ships on admin-authored pairings only. The spec's ranking blends a mined co-purchase
-- confidence with these, but mining is a later upgrade and not a prerequisite -- a curated
-- pairing enters at confidence 1.0, which is exactly what a mined one can never beat.

create table upsell_rule (
    id                   bigint        generated by default as identity primary key,
    trigger_product_id   bigint        not null references product (id),
    suggested_product_id bigint        not null references product (id),
    -- A suggestion that would dilute the deal is worse than none. Below this the
    -- candidate is dropped however well it pairs.
    min_margin_pct       numeric(5, 2) not null default 0,
    promoted             boolean       not null default false,
    constraint uq_upsell_pair unique (trigger_product_id, suggested_product_id),
    constraint ck_upsell_not_self check (trigger_product_id <> suggested_product_id)
);

-- Dismissing a card hides it for that quotation only, not for the product everywhere.
-- Surrogate key plus a unique pair, the same shape as stock_item: the pair is what matters,
-- but a single-column id keeps the mapping trivial.
create table quotation_dismissal (
    id           bigint generated by default as identity primary key,
    quotation_id bigint not null references quotation (id) on delete cascade,
    product_id   bigint not null references product (id),
    constraint uq_dismissal_quotation_product unique (quotation_id, product_id)
);

-- Six pairings. Products: 1 Laptop Pro, 2 Setup Service, 3 Support Plan,
-- 4 Docking Station, 5 Onsite Training.
insert into upsell_rule (trigger_product_id, suggested_product_id, min_margin_pct, promoted)
values (1, 4, 10, true),    -- a laptop wants a dock, and we are pushing docks
       (1, 3, 10, true),    -- and a support plan: the highest-margin line in the catalog
       (1, 2, 10, false),   -- setup service
       (4, 1, 10, false),   -- someone buying docks may not have bought the laptops yet
       (2, 5, 15, false),   -- setup leads to training
       (3, 5, 15, false);   -- so does a support plan
