-- A5 / B7: one order carries both line types.
--
-- One-time lines raise an invoice the moment the quotation is approved. Recurring lines
-- raise a subscription with twelve scheduled periods. There is deliberately no second
-- order table -- the fork is in how a line is billed, not in what the order is.

-- Which kind a line is follows its category, the same shape as `stockable`. Whether a
-- thing is billed monthly is a property of its kind, and keeping it in a table means it
-- stays configurable rather than compiled in.
alter table product_category
    add column recurring boolean not null default false;

update product_category set recurring = true where name = 'Subscriptions';

create table subscription (
    id           bigint         generated by default as identity primary key,
    quotation_id bigint         not null references quotation (id) on delete cascade,
    product_id   bigint         not null references product (id),
    quantity     int            not null check (quantity > 0),
    -- Per unit, per period, after the line's discount. The proration formula divides
    -- this by the days in a period -- never the whole line total.
    unit_price   numeric(14, 2) not null,
    status       varchar(20)    not null,
    start_date   date           not null,
    cancelled_at date,
    -- One subscription per recurring line, so the same product twice on one quotation
    -- stays two schedules rather than silently merging.
    constraint uq_subscription_quotation_product unique (quotation_id, product_id)
);

create table invoice (
    id           bigint         generated by default as identity primary key,
    quotation_id bigint         not null references quotation (id) on delete cascade,
    status       varchar(20)    not null,
    issued_at    timestamptz    not null default now()
);

create table invoice_line (
    id          bigint         generated by default as identity primary key,
    invoice_id  bigint         not null references invoice (id) on delete cascade,
    product_id  bigint         references product (id),
    description varchar(200)   not null,
    quantity    int            not null,
    unit_price  numeric(14, 2) not null,
    discount_pct numeric(5, 2) not null default 0,
    net_total   numeric(14, 2) not null,
    -- Added by a mid-period quantity increase rather than by the original order.
    proration   boolean        not null default false
);

create table billing_period (
    id              bigint         generated by default as identity primary key,
    subscription_id bigint         not null references subscription (id) on delete cascade,
    period_start    date           not null,
    period_end      date           not null,
    amount          numeric(14, 2) not null,
    status          varchar(20)    not null,
    invoice_id      bigint         references invoice (id),
    -- The nightly close is keyed on this pair, so a re-run cannot bill the same period
    -- twice however many times it fires.
    constraint uq_period_subscription_start unique (subscription_id, period_start)
);

create table payment (
    id          bigint         generated by default as identity primary key,
    invoice_id  bigint         not null references invoice (id) on delete cascade,
    amount      numeric(14, 2) not null check (amount > 0),
    reference   varchar(120),
    recorded_by bigint         not null references app_user (id),
    recorded_at timestamptz    not null default now()
);

create table credit_note (
    id         bigint         generated by default as identity primary key,
    invoice_id bigint         not null references invoice (id) on delete cascade,
    amount     numeric(14, 2) not null check (amount > 0),
    reason     varchar(300)   not null,
    issued_at  timestamptz    not null default now()
);

create index idx_invoice_quotation on invoice (quotation_id);
create index idx_period_subscription on billing_period (subscription_id, period_start);

-- The demo cannot wait a month for a period to fall due, so the nightly job takes the
-- date to bill up to. This row is that date; the admin action moves it forward one cycle
-- and runs the same job. Empty means "use today", which is what production does.
insert into system_config (key, value) values ('billing.clock', '');
